spring.application.name=springboot_tutorial

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=springBootDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=Anwer
spring.datasource.password=A@01126324374@n
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

